### ISSUE TITLE
CSV writer only writes headers.

### ISSUE THREAD

**Issue by kp2401075** [ritchie46/polars#370]
After doing some manipulation of DataFrame, when writing CSV file out. CSV writer is only writing headers not the data.

I can see data when printing df but CSV output only shows headers.

Most likely I'm doing something wrong. if so could you please point me in the right direction.

code is based on example on docs.rs
![image](https://user-images.githubusercontent.com/20717654/109233756-89222380-781e-11eb-8d1f-4145d0cea71a.png)

Code
```rust
use polars::prelude::*;
use std::fs::File;
// use std::io::Write;
// use std::path::Path;


fn read_csv() -> Result<DataFrame> {

 
      // just checks if unwrap doesn't panic
      CsvReader::from_path("/home/jayu/Projects/learn_rust/polars_test/Sample_Report_Final.csv")?
      .infer_schema(None)
       .has_header(true)
       .finish()

}
fn write_csv(df: &mut DataFrame) -> Result<()>{

   let mut file = File::create("example.csv").expect("could not create file");

    CsvWriter::new(&mut file)
    .has_headers(true)
    .finish(df)
}


fn main(){
    let mut df = read_csv().unwrap();
    println!("{:?}", df.head(Some(10)));
    // let x: Option<&[String]> = Some();
    let df = df.drop_nulls(Some(&[String::from("Jira Id")])).unwrap();
    println!("{:?}", df.head(Some(10)));
    let mut dg = df.select(&["Project","Jira Id", "Quote - OOM", "Consumed"]).unwrap();
    println!("{:?}", dg.head(Some(5)));
    write_csv(&mut dg);
  
    
}

```
output on terminal
``` bash
shape: (5, 4)
╭───────────────────────────────────────┬────────────┬─────────────┬────────────╮
│ Project                               ┆ Jira Id    ┆ Quote - OOM ┆ Consumed   │
│ ---                                   ┆ ---        ┆ ---         ┆ ---        │
│ str                                   ┆ str        ┆ str         ┆ str        │
╞═══════════════════════════════════════╪════════════╪═════════════╪════════════╡
│ "CRP0051338 -"                      ┆ "CEI1-101" ┆ "15,000"   ┆ "15,000"  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "B2B Support .."                      ┆ "CEI1-101" ┆ "230,000"  ┆ "15,145"  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "GBS -."                                ┆ "CEI1-101" ┆ "320,000"  ┆ "61,060"  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "CLSE30"                              ┆ "CEI1-102" ┆ null        ┆ "0"       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "OPC."                                  ┆ "5"        ┆ "496,000"  ┆ "124,645" │
╰───────────────────────────────────────┴────────────┴─────────────┴────────────╯
```

Output CSV file.

```csv
Project,Jira Id,Quote - OOM,Consumed

```

**Comment by kp2401075** [comment]
Ok here is more info

change in code for error handling
```rust
fn main(){
    let mut df = read_csv().unwrap();
    println!("{:?}", df.head(Some(10)));
    // let x: Option<&[String]> = Some();
    let df = df.drop_nulls(Some(&[String::from("Jira Id")])).unwrap();
    println!("{:?}", df.head(Some(10)));
    let mut dg = df.select(&["Project","Jira Id", "Quote - OOM", "Consumed"]).unwrap();
    println!("{:?}", dg.head(Some(5)));
    let f = write_csv(&mut dg);
    let f = match f {
        Ok(f) => println!("Fine"),
        Err(error) => panic!("Failed to write {:?}", error),
    };

  
    
}
```
Output
```bash
thread 'main' panicked at 'Failed to write ArrowError(CsvError("CSV Writer does not support LargeUtf8 data type"))', src/main.rs:38:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by kp2401075** [comment]
May be related to this,

https://github.com/ritchie46/polars/issues/333

trying following changes in Cargo.toml
```toml
[package]
name = "polars_test"
version = "0.1.0"
authors = ["Jay Patel <kp2401075@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

polars = {git="https://github.com/ritchie46/polars.git", features = ["random", "ndarray"]}
#reqwest = {version = "0.10.8", features = ["blocking"]}
ndarray = "0.13"
itertools = "0.9"
#tokio = "1.2.0"
```
